#!/usr/bin/env python3
"""
generate_autounattend.py

Gerador simples de Autounattend.xml a partir de parâmetros.

Uso exemplo:
  py -3 tools/generate_autounattend.py --os "Windows 10" --edition "Pro" --image "Windows 10 Pro" --out Autounattend_Win10_Pro.xml

O script cria um Autounattend.xml com valores substituíveis. NUNCA injete senhas/keys reais em repositórios públicos.
"""
import argparse
from datetime import datetime

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by generate_autounattend.py on {generated_at} -->
<unattend xmlns="urn:schemas-microsoft-com:unattend">
  <settings pass="windowsPE">
    <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <ImageInstall>
        <OSImage>
          <InstallFrom>
            <MetaData>
              <Key>/IMAGE/NAME</Key>
              <Value>{image_name}</Value>
            </MetaData>
          </InstallFrom>
        </OSImage>
      </ImageInstall>
      <DiskConfiguration>
        <Disk wcm:action="add" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
          <DiskID>0</DiskID>
          <WillWipeDisk>true</WillWipeDisk>
          <CreatePartitions>
            <CreatePartition>
              <Order>1</Order>
              <Type>Primary</Type>
              <Size>100</Size>
            </CreatePartition>
            <CreatePartition>
              <Order>2</Order>
              <Type>Primary</Type>
              <Extend>true</Extend>
            </CreatePartition>
          </CreatePartitions>
        </Disk>
        <WillShowUI>OnError</WillShowUI>
      </DiskConfiguration>
      <UserData>
        <AcceptEula>true</AcceptEula>
        <FullName>{owner}</FullName>
        <Organization>{org}</Organization>
        <ProductKey></ProductKey>
      </UserData>
    </component>
  </settings>

  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <ComputerName>{computer_name}</ComputerName>
      <UserAccounts>
        <LocalAccounts>
          <LocalAccount wcm:action="add" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
            <Name>{username}</Name>
            <DisplayName>{display_name}</DisplayName>
            <Password>
              <Value></Value>
              <PlainText>true</PlainText>
            </Password>
            <Group>Administrators</Group>
          </LocalAccount>
        </LocalAccounts>
      </UserAccounts>
    </component>
  </settings>

  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>{locale}</InputLocale>
      <SystemLocale>{locale}</SystemLocale>
      <UILanguage>{locale}</UILanguage>
      <UserLocale>{locale}</UserLocale>
    </component>
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <HideEULAPage>true</HideEULAPage>
        <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
        <ProtectYourPC>3</ProtectYourPC>
      </OOBE>
      <RegisteredOrganization>{org}</RegisteredOrganization>
      <RegisteredOwner>{owner}</RegisteredOwner>
    </component>
  </settings>

  <cpi:offlineImage cpi:source="wim:c:/sources/install.wim#{image_name}" xmlns:cpi="urn:schemas-microsoft-com:cpi" />
</unattend>
"""


def render(params):
    return TEMPLATE.format(**params)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--os', default='Windows 10', help='OS label')
    p.add_argument('--edition', default='Pro', help='Edition')
    p.add_argument('--image', default=None, help='Image name shown in WIM (e.g. "Windows 10 Pro")')
    p.add_argument('--locale', default='en-US')
    p.add_argument('--computer-name', default='WIN-AUTO')
    p.add_argument('--username', default='autouser')
    p.add_argument('--display-name', default='Auto User')
    p.add_argument('--owner', default='Owner')
    p.add_argument('--org', default='Organization')
    p.add_argument('--out', default=None, help='Output file path')

    args = p.parse_args()

    image_name = args.image or f"{args.os} {args.edition}"
    params = {
        'generated_at': datetime.utcnow().isoformat() + 'Z',
        'image_name': image_name,
        'owner': args.owner,
        'org': args.org,
        'computer_name': args.computer_name,
        'username': args.username,
        'display_name': args.display_name,
        'locale': args.locale,
    }

    out = args.out or f'Autounattend_{args.os.replace(" ","")}_{args.edition}.xml'
    content = render(params)
    with open(out, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'Wrote {out}')


if __name__ == '__main__':
    main()
